name: Deploy to Github Pages
on:
  push:
    branches: ["master"]
  workflow_dispatch:
jobs:
  deploy:
    name: Deploying to Github Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install packages
        run: npm i
      - name: Set Creds
        run: git config user.name "antonio0sarmientos" && git config user.email "samuel.a.toledo.s@gmail.com"
      - name: Deploying to gh-pages
        run: npm run deploy
